---
-
  connection: local
  gather_facts: false
  hosts: Orange
  name: "Backup running Config on Orange"
  tasks:
    -
      name: "backup current configuration"
      vyos_config:
        backup: true
