---
- name: Push Completed Config to Exeter
  hosts: Blueberry
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Push Completed  to Blueberry
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=blueberry.conf
        user={{ ansible_ssh_user }}
        passwd={{ ansible_ssh_pass}}

      - name: Display interfaces to CLI log file
        - junos_cli:
           host={{ansible_ssh_host}} user={{ansible_ssh_user}} passwd={{ansible_ssh_pass}}
           cli="show interfaces terse"
           logfile=cli.log
           dest="{{ ansible_ssh_host }}"
