---
- hosts: BlackCurrant
  gather_facts: false
  connection: local

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config

   - name: save output to /etc/ansible/backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "CiscoConfigs/show_run_{{ inventory_hostname }}.txt"
