---
-
  connection: local
  gather_facts: false
  hosts: BlackCurrant
  tasks:
    -
      ios_command:
        commands:
          - show running-config |  s interface GigabitEthernet2
        waitfor:
         - result[0] contains '172.16.10.5 255.255.255.0'
         - result[0] contains 'AREA1'
        host: "{{ ansible_ssh_host }}"
        password: "{{ ansible_ssh_pass }}"
        username: "{{ ansible_ssh_user }}"
      name: "Check GigabitEthernet2 has IP Address 172.16.10.5"
      register: interface2_result
    -
      debug:
        var: interface2_result.stdout_lines
      name: "Print GigabitEthernet2 response"
