---

- name: Test NAPALM on IOS
  hosts: BlackCurrant

  tasks:
    - name: "Gen .diff file (discard change)"
      napalm_install_config:
            host: "{{ ansible_ssh_host }}"
            password: "{{ ansible_ssh_pass }}"
            username: "{{ ansible_ssh_user }}"
            dev_os: ios
            config_file: initial.conf
            commit_changes: False
            replace_config: True
            diff_file: initial.diff 
