--- 
- 
  connection: local
  gather_facts: false
  hosts: BlackCurrant
  name: "Push Completed Config t Blackcurrant"
  tasks: 
    - 
      ios_config: 
        lines: 
          - router-id 3.3.3.3
          - network 172.16.1.0 0.0.0.255 area 0
          - network 172.16.10.0 0.0.0.255 area 1
        name: Push to BlackCurrant
        parents: router ospf 1
        provider: 
          host: "{{ ansible_ssh_host }}"
          password: "{{ ansible_ssh_pass}}"
          timeout: 20
          username: "{{ ansible_ssh_user }}"
    - 
      ios_command: 
        commands: 
          - show interfaces
        waitfor: 
          - result[0] contains 172.16.10.5
      name: "Show interfaces"
    - 
      ios_command: 
        commands: 
          - sh run | sec router ospf
        waitfor: 
          - result[0] contains 'router ospf 1
      name: "Show interfaces"
      register: cisco_result
    - 
      debug: 
        var: cisco_result.stdout_lines
      name: "Print OSPF response"
