--- 
- 
  connection: local
  gather_facts: false
  hosts: BlackCurrant
  name: "Push Completed Config t Blackcurrant"
  tasks: 
    - 
      ios_config: 
        lines: 
          - hostname billy
        parents: interface GigabitEthernet2
        provider: 
          host: "{{ ansible_ssh_host }}"
          password: "{{ ansible_ssh_pass}}"
          timeout: 10
          username: "{{ ansible_ssh_user }}"
      name: "Push to BlackCurrant"
    - 
      ios_command: 
        commands: 
          - show interfaces
        waitfor: 
          - result[0] contains GigabitEthernet2
      name: "Show interfaces"
      register: cisco_result
    - 
      debug: 
        var: cisco_result.stdout_lines
      name: "Print OSPF response"
