--- 
- 
  connection: local
  gather_facts: false
  hosts: BlackCurrant
  tasks: 
    - 
      ios_config: 
        host: "{{ ansible_ssh_host }}"
        lines: 
        - description AREA1
        - ip address 172.16.10.5 255.255.255.0
        - no shutdown
        parents: interface GigabitEthernet2
        password: "{{ ansible_ssh_pass }}"
        username: "{{ ansible_ssh_user }}"
      name: "configure Gig2 settings"
    - 
      ios_config: 
        host: "{{ ansible_ssh_host }}"
        lines: 
          - description AREA0
          - ip address 172.16.1.3 255.255.255.0
          - ip ospf priority 100
          - no shutdown
        parents: interface GigabitEthernet3
        password: "{{ ansible_ssh_pass }}"
        username: "{{ ansible_ssh_user }}"
      name: "configure Gig3 Settings"
    - 
      ios_command: 
        commands: 
          - "write memory"
        host: "{{ ansible_ssh_host }}"
        password: "{{ ansible_ssh_pass }}"
        username: "{{ ansible_ssh_user }}"
      name: "write mem"

