---

- hosts: Banana
  remote_user: cumulus
  gather_facts: 'no'
  become: 'yes'

  vars:
    ansible_become_pass: "Clouds123"

  tasks:
    - name: copy ports.conf
      copy: src=backup/{{inventory_hostname}}/ports.conf
            dest=/etc/cumulus/

    - name: copy interfaces
      copy: src=backup/{{inventory_hostname}}/interfaces
            dest=/etc/network/

    - name: copy frr daemons
      copy: src=backup/{{inventory_hostname}}/daemons
            dest=/etc/frr/

    - name: copy frr conf
      copy: src=backup/{{inventory_hostname}}/frr.conf
            dest=/etc/frr/

    - name: reload switchd
      service: name=switchd state=restarted

    - name: reload networking
      command: ifreload -a

    - name: reload frr
      service: name=frr state=restarted
