---
-
  connection: local
  hosts: Ireland
  name: "Test NAPALM on Vyos"
  tasks:
    - name: Gen .diff file discard change)
      napalm_install_config:
            host: "{{ ansible_ssh_host }}"
            username: "{{ ansible_ssh_user }}"
            password: "{{ ansible_ssh_pass }}"
            dev_os: vyos
            config_file: vyos.cfg
            commit_changes: False
            replace_config: True
            diff_file: initial.diff



     #commit_changes: false
     #config_file: initial.conf
     # dev_os: ios
     # diff_file: initial.diff
     # host: "{{ ansible_ssh_host }}"
     # napalm_install_config: ~
     # password: "{{ ansible_ssh_pass }}"
     # replace_config: true
     # username: "{{ ansible_ssh_user }}"
