---
-
  connection: local
  hosts: Orange
  name: "Test NAPALM on Vyos"
  tasks:
    - name: Gen .diff file discard change)
      napalm_install_config:
            host: "{{ ansible_ssh_host }}"
            username: "{{ ansible_ssh_user }}"
            password: "{{ ansible_ssh_pass }}"
            dev_os: vyos
            config_file: vyosreset.cfg
            commit_changes: True
            replace_config: True
            diff_file: basevrunning.diff

    -
      vyos_command:
        commands:
          - show interfaces
      name: "show interfaces"
      register: VyOS_result

    -
      debug:
        var: VyOS_result.stdout_lines
      name: "Print response"


     #commit_changes: false
     #config_file: initial.conf
     # dev_os: ios
     # diff_file: initial.diff
     # host: "{{ ansible_ssh_host }}"
     # napalm_install_config: ~
     # password: "{{ ansible_ssh_pass }}"
     # replace_config: true
     # username: "{{ ansible_ssh_user }}"
