---
-
  connection: local
  gather_facts: false
  hosts: Orange
  name: "Push Completed Config to Blueberry"
  tasks:
    -
      vyos_command:
        commands:
          - show version
          - show hardware cpu
        wait_for:
         - "result[0] contains 'VyOS 1.1.8'"
      name: "run multiple commands and check if version output contains specific version string"
      register: VyOS_result
    -
      debug:
        var: VyOS_result.stdout_lines
      name: "Print OSPF response"
