---
  - name: BACKUP configurations
    hosts: Exeter
    roles:
    - Juniper.junos
    gather_facts: no
    connection: local

    tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830  timeout=6

    - name: SAVE AND BACKUP CONFIGS
      junos_config:
        backup=yes
        host={{ inventory_hostname }}
        username={{ ansible_ssh_user }}
        password={{ ansible_ssh_pass }}
