---
- name: Get Device Facts
  hosts: Exeter
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ ansible_ssh_host }} port=830 timeout=5

  tasks:
    - name: Push Default to Exeter
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=/etc/ansible/EXE.conf
        user=root
        passwd=Clouds123
