---
-
  connection: local
  hosts: England
  name: "England commit master"
  tasks:
    - name: Reset to base
      napalm_install_config:
            host: "{{ ansible_ssh_host }}"
            username: "{{ ansible_ssh_user }}"
            password: "{{ ansible_ssh_pass }}"
            dev_os: ios
            config_file: base.conf
            commit_changes: True
            replace_config: True
