---
-
  connection: local
  hosts: England
  name: "England diff no commit"
  tasks:
    - name: NoCommit master England and diff_file
      napalm_install_config:
            host: "{{ ansible_ssh_host }}"
            username: "{{ ansible_ssh_user }}"
            password: "{{ ansible_ssh_pass }}"
            dev_os: ios
            config_file: master.conf
            commit_changes: False
            replace_config: True
            diff_file: inital.diff
